//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18051
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GadgeteerMtrCtrl {
    using Gadgeteer;
    using GTM = Gadgeteer.Modules;
    
    
    public partial class Program : Gadgeteer.Program {
        
        private Gadgeteer.Modules.GHIElectronics.MulticolorLed multicolorLed;
        
        private Gadgeteer.Modules.GHIElectronics.MulticolorLed multicolorLed1;
        
        private Gadgeteer.Modules.GHIElectronics.UsbClientDP usbClientDP;
        
        public static void Main() {
            // Important to initialize the Mainboard first
            Program.Mainboard = new GHIElectronics.Gadgeteer.FEZSpider();
            Program p = new Program();
            p.InitializeModules();
            p.ProgramStarted();
            // Starts Dispatcher
            p.Run();
        }
        
        private void InitializeModules() {
            this.usbClientDP = new GTM.GHIElectronics.UsbClientDP(1);
            this.multicolorLed1 = new GTM.GHIElectronics.MulticolorLed(10);
            this.multicolorLed = new GTM.GHIElectronics.MulticolorLed(11);
        }
    }
}
